from django import forms

class CreateBoletimEpidemiologicoForm(forms.Form):
    cidade = forms.CharField(max_length=256)
    data_atualizacao = forms.DateTimeField()
    fonte_oficial_url = forms.URLField()
    fonte_oficial_tipo = forms.CharField(max_length=256)
    confirmados = forms.IntegerField(required=False)
    conf_reside = forms.IntegerField(required=False)
    conf_nao_reside = forms.IntegerField(required=False)
    recuperados = forms.IntegerField(required=False)
    obitos = forms.IntegerField(required=False)
    isolados = forms.IntegerField(required=False)
    iso_domiciliar = forms.IntegerField(required=False)
    iso_hospitalar = forms.IntegerField(required=False)
    iso_hosp_sus = forms.IntegerField(required=False)
    iso_hosp_priv = forms.IntegerField(required=False)
    iso_hosp_sus_enf = forms.IntegerField(required=False)
    iso_hosp_priv_enf = forms.IntegerField(required=False)
    iso_hosp_sus_uti = forms.IntegerField(required=False)
    iso_hosp_priv_uti = forms.IntegerField(required=False)
    suspeitos = forms.IntegerField(required=False)
    sus_isolados = forms.IntegerField(required=False)
    sus_iso_domiciliar = forms.IntegerField(required=False)
    sus_iso_hospitalar = forms.IntegerField(required=False)
    sus_investigados = forms.IntegerField(required=False)
    testados = forms.IntegerField(required=False)
    test_pcr = forms.IntegerField(required=False)
    test_rapido = forms.IntegerField(required=False)
    descartados = forms.IntegerField(required=False)
    monitorados = forms.IntegerField(required=False)
    notificados = forms.IntegerField(required=False)