# Generated by Django 3.0.6 on 2020-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_graficos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
