# Generated by Django 3.0.6 on 2020-05-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chartbuilder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChartBuilder',
            new_name='ParametersChartBuilder',
        ),
    ]
