# Generated by Django 3.0.6 on 2020-05-24 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chartbuilder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletimepidemiologico',
            old_name='recupados',
            new_name='recuperados',
        ),
    ]
