# Generated by Django 3.0.6 on 2020-05-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200524_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletimepidemiologico',
            name='data_atualizacao',
            field=models.DateTimeField(verbose_name='Data de atualização'),
        ),
    ]
