# Generated by Django 3.0.7 on 2020-06-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200530_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametersChartBuilder',
        ),
    ]
