# Generated by Django 3.0.5 on 2020-06-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200524_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletimepidemiologico',
            old_name='fonte_oficial',
            new_name='fonte_oficial_url',
        ),
        migrations.RenameField(
            model_name='boletimepidemiologico',
            old_name='investigados',
            new_name='sus_investigados',
        ),
        migrations.RemoveField(
            model_name='boletimepidemiologico',
            name='enfermaria',
        ),
        migrations.RemoveField(
            model_name='boletimepidemiologico',
            name='internados',
        ),
        migrations.RemoveField(
            model_name='boletimepidemiologico',
            name='uti',
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='conf_nao_reside',
            field=models.PositiveIntegerField(null=True, verbose_name='Confirmados que não residem na cidade'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='conf_reside',
            field=models.PositiveIntegerField(null=True, verbose_name='Confirmados que residem na cidade'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='fonte_oficial_tipo',
            field=models.CharField(default='Prefeitura', max_length=256, verbose_name='Fonte Oficial (Tipo)'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='iso_domiciliar',
            field=models.PositiveIntegerField(null=True, verbose_name='Isolados domiciliar'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='iso_hosp_priv',
            field=models.PositiveIntegerField(null=True, verbose_name='Isolados hospitalar privado'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='iso_hosp_priv_enf',
            field=models.PositiveIntegerField(null=True, verbose_name='Isolados hospitalar privado enfermaria'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='iso_hosp_priv_uti',
            field=models.PositiveIntegerField(null=True, verbose_name='Isolados hospitalar privado UTI'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='iso_hosp_sus',
            field=models.PositiveIntegerField(null=True, verbose_name='Isolados hospitalar SUS'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='iso_hosp_sus_enf',
            field=models.PositiveIntegerField(null=True, verbose_name='Isolados hospitalar SUS enfermaria'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='iso_hosp_sus_uti',
            field=models.PositiveIntegerField(null=True, verbose_name='Isolados hospitalar SUS UTI'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='iso_hospitalar',
            field=models.PositiveIntegerField(null=True, verbose_name='Isolados hospitalar'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='sus_iso_domiciliar',
            field=models.PositiveIntegerField(null=True, verbose_name='Suspeitos isolados domiciliar'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='sus_iso_hospitalar',
            field=models.PositiveIntegerField(null=True, verbose_name='Suspeitos isolados hospitalar'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='sus_isolados',
            field=models.PositiveIntegerField(null=True, verbose_name='Suspeitos isolados'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='test_pcr',
            field=models.PositiveIntegerField(null=True, verbose_name='Testados RT-PCR'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='test_rapido',
            field=models.PositiveIntegerField(null=True, verbose_name='Testados TR-Igm/Igg'),
        ),
        migrations.AddField(
            model_name='boletimepidemiologico',
            name='testados',
            field=models.PositiveIntegerField(null=True, verbose_name='Testados'),
        ),
    ]
