# Generated by Django 3.0.7 on 2020-07-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_parameterschartbuilder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
