# Generated by Django 3.0.7 on 2020-07-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200619_1645'),
        ('core', '0005_delete_parameterschartbuilder'),
    ]

    operations = [
    ]
