from .graficos import Graficos
from .boletimEpidemiologico import BoletimEpidemiologico
from .home import Home
from .comparacao import Comparacao
from .como_sao_criados import ComoSaoCriados
from .sobre import Sobre
from .na_midia import NaMidia
from .colabore import Colabore
from .tendencias import Tendencias
from .equipe import Equipe
from .noticias import Noticias
from .chartbuilder import ChartBuilder
from .simulacao import Simulacao